"""add asset metadata

Revision ID: 92ef47bc5b07
Revises: c53635f84e82
Create Date: 2026-09-10 10:40:44.251831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '92ef47bc5b07'
down_revision: Union[str, Sequence[str], None] = 'c53635f84e82'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('stocks', sa.Column('logo_url', sa.String(), nullable=True))
    op.add_column('stocks', sa.Column('is_featured', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'is_featured')
    op.drop_column('stocks', 'logo_url')
    op.drop_column('stocks', 'currency')
    # ### end Alembic commands ###
